spring:
  application:
    name: identity-service

  datasource:
    url: "jdbc:mysql://localhost:3301/identity_service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
  servlet:
    context-path: /identity

jwt:
  signerKey: "hRvc9cgVqAb6QgI7lLllt+PoEQ2U9AwlUXZCqB7rBvUsRLpmzdE+/WdbvqfwlJWO"